#!/usr/bin/env python3
"""Render a disposable Mermaid view from knowledge-note links."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from kb_index import KNOWLEDGE_DIR, load_notes  # noqa: E402
from lib.knowledge import KnowledgeNote, local_links  # noqa: E402


DEFAULT_OUTPUT = KNOWLEDGE_DIR / "_graph.md"


def _relative_path(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _node_id(path: Path, root: Path) -> str:
    digest = hashlib.sha1(_relative_path(path, root).encode("utf-8")).hexdigest()[:10]
    return f"n_{digest}"


def _label(value: str) -> str:
    return value.replace("\\", "/").replace('"', "&quot;")


def render_graph(notes: list[KnowledgeNote] | tuple[KnowledgeNote, ...], *, root: Path = ROOT) -> str:
    """Return deterministic GitHub-compatible Mermaid Markdown."""

    root = root.resolve()
    note_by_path = {note.path.resolve(): note for note in notes}
    graph_paths = set(note_by_path)
    edges: set[tuple[Path, Path]] = set()

    for note in sorted(notes, key=lambda item: _relative_path(item.path, root)):
        source = note.path.resolve()
        for target, _anchor in local_links(note.body):
            target_path = Path(unquote(target))
            if "data" in target_path.parts:
                continue
            resolved = (source.parent / target_path).resolve()
            try:
                resolved.relative_to(root)
            except ValueError:
                continue
            if not resolved.is_file() or resolved.suffix.lower() != ".md":
                continue
            graph_paths.add(resolved)
            edges.add((source, resolved))

    lines = [
        "# Knowledge Graph",
        "",
        "Generated by `make kb-graph`; Markdown notes and links remain the source of truth.",
        "",
        "```mermaid",
        "graph LR",
        "  classDef note fill:#dbeafe,stroke:#2563eb,color:#111827",
        "  classDef owner fill:#fef3c7,stroke:#d97706,color:#111827",
    ]

    for path in sorted(graph_paths, key=lambda item: _relative_path(item, root)):
        relative = _relative_path(path, root)
        note = note_by_path.get(path)
        label = note.title if note else relative
        role = "note" if note else "owner"
        lines.append(f'  {_node_id(path, root)}["{_label(label)}"]:::{role}')

    for source, target in sorted(
        edges,
        key=lambda pair: (_relative_path(pair[0], root), _relative_path(pair[1], root)),
    ):
        lines.append(f"  {_node_id(source, root)} --> {_node_id(target, root)}")

    lines.extend(["```", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=KNOWLEDGE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args(argv)

    expected = render_graph(load_notes(args.directory), root=ROOT)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
            print(f"[Status: Warning] {args.output} is missing or stale — run make kb-graph")
            return 1
        print(f"[Status: OK] {args.output} is current")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"[Status: OK] wrote {args.output} ({len(load_notes(args.directory))} source notes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
