#!/usr/bin/env python3
"""Build a compact knowledge catalog and run deterministic lexical search."""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from lib.knowledge import KnowledgeNote, iter_note_paths, load_note  # noqa: E402


KNOWLEDGE_DIR = ROOT / "docs" / "knowledge"
DEFAULT_MIN_TERM_COVERAGE = 0.5
_TOKEN_RE = re.compile(r"[\w-]+", re.UNICODE)
_STOPWORDS = frozenset(
    "a an and are as at be by do does for from how in is it of on or that the their this to what "
    "where which with should can may".split()
)
_FIELD_WEIGHTS = (
    ("filename", 8),
    ("title", 8),
    ("summary", 5),
    ("headings", 3),
    ("body", 1),
)


@dataclass(frozen=True)
class SearchResult:
    note: KnowledgeNote
    score: int
    matched_fields: tuple[str, ...]


def _tokens(value: str) -> set[str]:
    return {
        _canonical_token(token.lower())
        for token in _TOKEN_RE.findall(value)
        if token.lower() not in _STOPWORDS
    }


def _canonical_token(token: str) -> str:
    """Apply a deliberately small, dependency-free English normalisation."""

    if token.endswith("ation") and len(token) > 7:
        return token[:-5]
    if token.endswith("ing") and len(token) > 5:
        stem = token[:-3]
        return stem + "e" if stem.endswith("t") else stem
    if token.endswith("es") and len(token) > 4:
        return token[:-2]
    if token.endswith("s") and len(token) > 3:
        return token[:-1]
    return token


def _field_text(note: KnowledgeNote) -> dict[str, str]:
    return {
        "filename": note.path.stem.replace("_", " ").replace("-", " "),
        "title": note.title,
        "summary": str(note.metadata.get("summary", "")),
        "headings": " ".join(note.headings),
        "body": note.body,
    }


def search_notes(
    query: str,
    notes: list[KnowledgeNote] | tuple[KnowledgeNote, ...],
    *,
    limit: int = 3,
    include_superseded: bool = False,
    min_term_coverage: float = DEFAULT_MIN_TERM_COVERAGE,
) -> list[SearchResult]:
    """Return deterministic, compact lexical matches for a question."""

    terms = _tokens(query)
    if not terms or limit <= 0:
        return []
    if not 0.0 <= min_term_coverage <= 1.0:
        raise ValueError("min_term_coverage must be between 0 and 1")

    results: list[SearchResult] = []
    for note in notes:
        if not include_superseded and note.metadata.get("status") == "superseded":
            continue
        fields = _field_text(note)
        score = 0
        matched: list[str] = []
        matched_terms: set[str] = set()
        for field, weight in _FIELD_WEIGHTS:
            overlap = terms & _tokens(fields[field])
            if overlap:
                score += weight * len(overlap)
                matched.append(field)
                matched_terms.update(overlap)
        coverage = len(matched_terms) / len(terms)
        if score and coverage >= min_term_coverage:
            results.append(SearchResult(note, score, tuple(matched)))

    status_rank = {"active": 0, "draft": 1, "superseded": 2}
    results.sort(
        key=lambda result: (
            -result.score,
            status_rank.get(str(result.note.metadata.get("status")), 9),
            result.note.path.as_posix(),
        )
    )
    return results[:limit]


def load_notes(directory: Path = KNOWLEDGE_DIR) -> tuple[KnowledgeNote, ...]:
    return tuple(load_note(path) for path in iter_note_paths(directory))


def _relative_path(path: Path, root: Path = ROOT) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def render_search_results(results: list[SearchResult], *, root: Path = ROOT) -> str:
    return "\n".join(
        " | ".join(
            (
                _relative_path(result.note.path, root),
                result.note.title,
                str(result.note.metadata.get("type", "")),
                str(result.note.metadata.get("status", "")),
                str(result.note.metadata.get("summary", "")),
                str(result.score),
            )
        )
        for result in results
    )


def render_catalog(notes: tuple[KnowledgeNote, ...], *, root: Path = ROOT) -> str:
    lines = [
        "# Knowledge Catalog",
        "",
        "Generated by `make kb-index`; Markdown notes remain the source of truth.",
        "",
        "| Path | Title | Type | Status | Summary |",
        "|---|---|---|---|---|",
    ]
    for note in notes:
        fields = (
            f"[{_relative_path(note.path, root)}]({_relative_path(note.path, root)})",
            note.title,
            str(note.metadata.get("type", "")),
            str(note.metadata.get("status", "")),
            str(note.metadata.get("summary", "")).replace("|", "\\|"),
        )
        lines.append("| " + " | ".join(fields) + " |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=KNOWLEDGE_DIR)
    parser.add_argument("--query", help="search question; omit to render the catalog")
    parser.add_argument("--limit", type=int, default=3)
    parser.add_argument("--min-term-coverage", type=float, default=DEFAULT_MIN_TERM_COVERAGE)
    parser.add_argument("--write-catalog", action="store_true")
    args = parser.parse_args(argv)

    notes = load_notes(args.directory)
    if args.query:
        print(
            render_search_results(
                search_notes(args.query, notes, limit=args.limit, min_term_coverage=args.min_term_coverage)
            )
        )
        return 0

    catalog = render_catalog(notes)
    if args.write_catalog:
        output = args.directory / "_catalog.md"
        output.write_text(catalog, encoding="utf-8")
        print(f"[Status: OK] wrote {output.relative_to(ROOT)} ({len(notes)} notes)")
    else:
        print(catalog, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
